### ISSUE TITLE
No rounded covers

### ISSUE THREAD

**Issue by LiranDan** [dariolupo/Daze_Theme#16]
Hi,
First of all - thank you very much for your theme!

For some reason I don't have rounded covers at all. I made sure the Target aspect ratio is 3:4 and re-downloaded all covers from IGDB.
![Page](https://user-images.githubusercontent.com/46448299/232340955-96d36bd4-77b4-4e82-8053-3eb70dac32e8.JPG)

**Comment by dariolupo** [comment]
Hi. That's strange. Make sure to download the latest version of the theme, you can update it through Playnite. With the lastest version aspect ratio shouldn't matter at all.

**Comment by LiranDan** [comment]
Thank you for your response Dario.

I did actually install the theme from the playnite addon so I believe I have the last one. Version 2.1.2.

Any other suggestions that I could check? I really appreciate the help.

**Comment by dariolupo** [comment]
I honestly don't really know, rounded covers should work straight away since it's part of the theme's code. 

Do you have some theme editing add-on installed that might have broken stuff? There's nothing else I can think of. I suppose you already tried completely uninstalling and reinstalling the theme?

**Comment by LiranDan** [comment]
I realized what caused the issue.
The mod you've created for removing ratings in grid view broke it.

Is there any chance you can fix this mod? I will really really appreiciate your time and effort.

**Comment by dariolupo** [comment]
Ok, so that's probably it because with the latest version you no longer need that mod. You can now remove the stars by using the Theme Modifier add-on. I think completely uninstalling and reinstalling the theme will fix the issue, then you can use the Theme Modifier add-on you can find in Playnite to edit the theme.

**Comment by LiranDan** [comment]
Awesome, I've downloaded it and made the changes and it works flawlessly.
Thank you very much for your help Dario!

Is there anything else you think I should know? I just started using playnite.

**Comment by dariolupo** [comment]
Glad it worked!

Not really, if you want just join the Playnite Discord to interact with other users and learn things about it :)
